'use strict';
const fs = require('fs');
const fileName = './test.txt';

fs.appendFileSync(fileName, '▼しりとり20連発▼\n', 'utf8');
fs.appendFileSync(fileName, 'プログラム\n', 'utf8');
fs.appendFileSync(fileName, 'むし\n', 'utf8');
fs.appendFileSync(fileName, 'しか\n', 'utf8');
fs.appendFileSync(fileName, 'かば\n', 'utf8');
fs.appendFileSync(fileName, 'バリ\n', 'utf8');
fs.appendFileSync(fileName, 'りんご\n', 'utf8');
fs.appendFileSync(fileName, 'ゴリラ\n', 'utf8');
fs.appendFileSync(fileName, 'ラッパ\n', 'utf8');
fs.appendFileSync(fileName, 'パイナップル\n', 'utf8');
fs.appendFileSync(fileName, 'ルビー\n', 'utf8');
fs.appendFileSync(fileName, 'いか\n', 'utf8');
fs.appendFileSync(fileName, 'カエル\n', 'utf8');
fs.appendFileSync(fileName, 'るす\n', 'utf8');
fs.appendFileSync(fileName, 'すいか\n', 'utf8');
fs.appendFileSync(fileName, 'からす\n', 'utf8');
fs.appendFileSync(fileName, 'スイス\n', 'utf8');
fs.appendFileSync(fileName, 'スケート\n', 'utf8');
fs.appendFileSync(fileName, 'トマト\n', 'utf8');
fs.appendFileSync(fileName, 'とんぼ\n', 'utf8');
fs.appendFileSync(fileName, 'ぼろぞうきん\n', 'utf8');
